name = "MaximaMacro"
uuid = "94002945-a687-49bf-ad87-71bdff4e58e6" # generado por Pkg.generate
authors = ["Miguel √Ångel Rubio de Diego <imardiego@gmail.com>"]
version = "2.0.0"

[compat]
julia = "1.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"  # obtenido por Base.identify_package("Dates")

